### ISSUE TITLE
그룹 생성시 유저db 그룹권한 문제

### ISSUE THREAD

**Issue by SongGol** [GME-392/sanhak-server#18]
![image](https://user-images.githubusercontent.com/26537075/115235914-ad7eea00-a155-11eb-9fac-7726c66fe4c7.png)
그룹 생성시 유저db 그룹권한이 false로 되어있음

**Comment by C17AN** [comment]
감사합니다!
이렇게 남겨두지 않으면 제가 또 까먹어서요 ^___^

**Comment by SongGol** [comment]
default 권한을 true로 수정
