### ISSUE TITLE
그룹 생성 시 group_member에 추가 안되는 문제

### ISSUE THREAD

**Issue by C17AN** [GME-392/sanhak-server#22]
![image](https://user-images.githubusercontent.com/26535030/116805348-ef9a2980-ab60-11eb-9e59-17402644ebe4.png)

해결 부탁드립니다.

**Comment by jane-k** [comment]
이건 해결 했어요

**Comment by C17AN** [comment]
![image](https://user-images.githubusercontent.com/26535030/116805922-ac41ba00-ab64-11eb-9c1e-0282e10715d4.png)

어제 논의한대로면 
"group_member" : [
  "kimtaehyun98" : {
    "name" : "kimtaehyun98",
    "rank" : 2701,
    "attendance" : false
  }
]

이런 식으로 구현되어야 할텐데, 확인 부탁드릴게요

**Comment by C17AN** [comment]
![image](https://user-images.githubusercontent.com/26535030/116819498-4167a180-abab-11eb-87ac-cb2af4ca76f3.png)

그룹 생성 시, 여전히 그룹 생성자가 멤버 리스트에 추가되지 않는 문제가 있습니다.
확인 부탁드릴게요!
